- hosts: webservers
  tasks:
  - name: Installing Latest version of Apache
    yum: name=httpd state=latest

  - name: Copying the Index file
    template: src=../examples/index.html dest=/var/www/html owner=apache group=apache mode=0644

  - name: Copying info.php file
    template: src=../examples/info.php dest=/var/www/html owner=apache group=apache mode=0644


  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes

  - name: Installed Packages
    yum: pkg={{ item }} state=installed
    with_items:
        - mariadb-server
        - mariadb
        - php
        - php-mysql
        - wget

  - name: Ensure MariaDB is running (and enable it at boot)
    service: name=mariadb state=started enabled=yes

    notify:
    - restart MariaDB

    notify:
    - restart apache


  handlers:
    - name: restart apache
      service: name=httpd state=restarted

    - name: restart MariaDB
      service: name=mariadb state=restarted